repos:
-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
